export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MATCH_DATA = "GET_MATCH_DATA";
export const GET_MATCH_DATA_BY_ID = "GET_MATCH_DATA_BY_ID";
export const GET_MATCH_DATA_BY_YEAR = "GET_MATCH_DATA_BY_YEAR";
export const GET_MATCH_DATA_BY_TEAM_NAME = "GET_MATCH_DATA_BY_TEAM_NAME";
export const CHANGE_THEME = "CHANGE_THEME";